// =============================================================================
// Diff rendering component — unified diff view with theme-aware coloring.
// Equivalent to Python tui.widgets.diff.
// =============================================================================

import React from "react";
import { Box, Text } from "ink";
import { getGlyphs } from "../terminal/config-ui.js";

// =============================================================================
// Props
// =============================================================================

export interface DiffViewProps {
  /** The unified diff text (generated by `diff` library or similar). */
  diffText: string;
  /** Optional title for the diff. */
  title?: string;
  /** Maximum number of lines to display. */
  maxLines?: number;
}

// =============================================================================
// Component
// =============================================================================

export const DiffView: React.FC<DiffViewProps> = ({
  diffText,
  title,
  maxLines = 50,
}) => {
  const glyphs = getGlyphs();
  const lines = diffText.split("\n");
  const displayLines = lines.slice(0, maxLines);
  const truncated = lines.length > maxLines;

  return (
    <Box flexDirection="column" borderStyle="round" borderColor="cyan" paddingX={1}>
      {/* Header */}
      {title && (
        <Box marginBottom={1}>
          <Text bold color="cyan">
            {glyphs.toolPrefix} {title}
          </Text>
        </Box>
      )}

      {/* Diff lines */}
      <Box flexDirection="column">
        {displayLines.map((line, i) => {
          const color = line.startsWith("+")
            ? "green"
            : line.startsWith("-")
            ? "red"
            : line.startsWith("@@")
            ? "cyan"
            : undefined;
          const bgColor = line.startsWith("+")
            ? "green"
            : line.startsWith("-")
            ? "red"
            : undefined;

          return (
            <Box key={i}>
              <Text color={color} backgroundColor={bgColor}>
                {line}
              </Text>
            </Box>
          );
        })}

        {/* Truncation notice */}
        {truncated && (
          <Box marginTop={1}>
            <Text dimColor>
              {glyphs.ellipsis} {lines.length - maxLines} more lines not shown
            </Text>
          </Box>
        )}
      </Box>
    </Box>
  );
};

// =============================================================================
// Diff line composition (reusable by other components)
// =============================================================================

/**
 * Decompose a diff string into styled lines.
 * Returns an array of { line, type } where type is "added", "removed", "context", or "header".
 *
 * Equivalent to Python `compose_diff_lines()`.
 */
export function composeDiffLines(diffText: string): { line: string; type: "added" | "removed" | "context" | "header" }[] {
  return diffText.split("\n").map((line) => {
    if (line.startsWith("+") && !line.startsWith("+++")) {
      return { line, type: "added" as const };
    }
    if (line.startsWith("-") && !line.startsWith("---")) {
      return { line, type: "removed" as const };
    }
    if (line.startsWith("@@")) {
      return { line, type: "header" as const };
    }
    return { line, type: "context" as const };
  });
}
